name: Jenkins Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  JENKINS_HOST: https://9dd3-209-133-48-2.ngrok-free.app ## jenkins base url
  JENKINS_JOB: git-demo ## builds the HelloWorld job inside testJobs

jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      -
        name: Trigger Jenkins Job
        uses: sbitio/trigger-jenkins-job@master
        with:
          JENKINS_USER: sanjay
          JENKINS_TOKEN: 11b94b8aa8d2bcf031c084dba199d3be67
          JENKINS_HOST: ${{ env.JENKINS_HOST }}
          JENKINS_JOB: ${{ env.JENKINS_JOB }}
