name: Jenkins Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  JENKINS_HOST: https://9dd3-209-133-48-2.ngrok-free.app ## jenkins base url
  JENKINS_JOB: git-demo ## builds the HelloWorld job inside testJobs

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Jenkins Job
        env:
          JENKINS_USERNAME: sanjay  # Replace with your Jenkins username
          JENKINS_TOKEN: 11b94b8aa8d2bcf031c084dba199d3be67  # Accessing the secret API token
        run: |
          curl -X POST "https://9dd3-209-133-48-2.ngrok-free.app/job/git-demo/build" \
            --user $JENKINS_USERNAME:$JENKINS_TOKEN
